name: Issue Workflow
on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        id: close_issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number:  ${{ github.event.issue.number }},
              state: 'closed'
            })

  robot_job:
    runs-on: ubuntu-latest
    needs: process_issue
    steps:
      - name: robot
        if: ${{ github.event.issue.title == 'next step' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://losehu:${{ secrets.GH_TOKEN }}@github.com/losehu/losehu.git main
          cd main
          chmod +x draw
          ./draw ${{ github.event.issue.number }} "${{ github.event.issue.body }}" "${{ secrets.GH_TOKEN }}"
          git remote set-url origin https://losehu:${{ secrets.GH_TOKEN }}@github.com/losehu/losehu.git
          git add .
          git commit -m "update"
          git push origin main --force
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
