name: Issue Workflow
on:
  issues:
    types: [opened]

jobs:
  process_issue:
    if: ${{ github.event.issue.title == '2048' }}
    runs-on: ubuntu-latest

    steps:
      - name: Comment and close issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for playing!Can you give me a star?'
            })
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number:  ${{ github.event.issue.number }},
              state: 'closed'
            })

            


      - name: robot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://losehu:${{ secrets.GH_TOKEN }}@github.com/losehu/losehu.git main
          cd main
          git checkout 2048
          chmod +x 2048
          ./2048 "${{ github.event.issue.body }}" 
          git remote set-url origin https://losehu:${{ secrets.GH_TOKEN }}@github.com/losehu/losehu.git
          git add .
          git commit -m "${{ github.event.issue.body }} by ${{ github.event.issue.user.login }}"
          git push origin 2048 --force
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
