name: Issue Workflow
on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: robot
        if: ${{ github.event.issue.title == 'next step' }}
        run: |
          chmod +x draw
          ./draw ${{ github.event.issue.number }} "${{ github.event.issue.body }}" "${{ secrets.GH_TOKEN }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}



      - name: Close issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number:  ${{ github.event.issue.number }},
              state: 'closed'
            })