name: Issue Workflow
on:
  issues:
    types: [opened]

jobs:
  process_issue:
    if: ${{ github.event.issue.title == '2048' }}
    runs-on: ubuntu-latest

    steps:
      - name: Comment and close issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for playing!Can you give me a star?'
            })
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number:  ${{ github.event.issue.number }},
              state: 'closed'
            })

      - name: Modify and commit
        uses: actions/checkout@v2
        
      - name: Modify and commit
        run: |
          chmod +x 2048
          ./2048 "${{ github.event.issue.body }}" "${{ github.event.issue.user.login }}"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ github.event.issue.body }} by ${{ github.event.issue.user.login }}"
          git push origin HEAD:2048
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
